### ISSUE TITLE
Causes my IP to be blocked 

### ISSUE THREAD

**Issue by Ar4g0rn** [dmzoneill/php-binance-bot#1]
Exception: signedRequest error: {"code":-1003,"msg":"**Way too much request weight used; IP banned until 1633627344042. Please use the websocket for live updates to avoid bans**."} in /root/php-binance-bot/bi-api.php:1139
Stack trace:
#0 /root/php-binance-bot/bi-api.php(906): Binance\API->httpRequest('v3/account', 'GET', Array, true)
#1 /root/php-binance-bot/BinanceBotHoldings.class.php(47): Binance\API->balances(Array)
#2 /root/php-binance-bot/BinanceBotHoldings.class.php(34): BinanceBot\BinanceBotHoldings->update()
#3 /root/php-binance-bot/Bot.class.php(47): BinanceBot\BinanceBotHoldings->__construct(Array)
#4 /root/php-binance-bot/binance-bot.class.php(9): Bot->__construct()
#5 /root/php-binance-bot/binance-bot.class.php(13): BinanceBot->__construct()
#6 {main}PHP Notice:  Undefined variable: updated in /root/php-binance-bot/BinanceBotHoldings.class.php on line 58
PHP Warning:  Invalid argument supplied for foreach() in /root/php-binance-bot/BinanceBotHoldings.class.php on line 174
 Candle updates remaining 1020 PHP Fatal error:  Uncaught Exception: signedRequest error: {"code":-1003,"msg":"Way too much request weight used; IP banned until 1633627344042. Please use the websocket for live updates to avoid bans."} in /root/php-binance-bot/bi-api.php:1139
Stack trace:
#0 /root/php-binance-bot/bi-api.php(1255): Binance\API->httpRequest('v1/klines', 'GET', Array)
#1 /root/php-binance-bot/BinanceBotCandles.class.php(170): Binance\API->candlesticks('WANUSDT', '3m')
#2 /root/php-binance-bot/BinanceBotCandles.class.php(76): BinanceBot\BinanceBotCandles->updateNext(false, true, false)
#3 /root/php-binance-bot/BinanceBotCandles.class.php(64): BinanceBot\BinanceBotCandles->update()
#4 /root/php-binance-bot/Bot.class.php(48): BinanceBot\BinanceBotCandles->__construct(Array)
#5 /root/php-binance-bot/binance-bot.class.php(9): Bot->__construct()
#6 /root/php-binance-bot/binance-bot.class.php(13): BinanceBot->__construct()
#7 {main}
  thrown in /root/php-binance-bot/bi-api.php on line 1139

**Comment by dmzoneill** [comment]
not relevant any more, but there was a rate limiter provided with the solution

**Comment by dmzoneill** [comment]
## Analysis

The error you're encountering is from Binance's API rate limiting system:

```
Exception: signedRequest error: {"code":-1003,"msg":"Way too much request weight used; IP banned until [timestamp]. Please use the websocket for live updates to avoid bans."}
```

This happens when your bot is making too many API requests in a short time window, consuming too much of your allocated request weight quota. Binance enforces strict rate limits to prevent abuse.

## Root Cause

Looking at your code, the issue is in **BinanceBotCandles.class.php** (line 170). The bot is making candlestick requests for **every trading pair** during each update cycle:

- The `updateNext()` function loops through all symbols
- For each symbol, it makes 3 candlestick API calls (3m, 15m, 1h intervals) 
- With potentially 100+ trading pairs, this quickly exceeds Binance's 1200 weight/minute limit

Additionally, **BinanceBotHoldings.class.php** (line 47) calls `$this->_api->balances()` frequently, which also consumes request weight.

## Solutions

### 1. **Increase Request Batching Intervals** (Quick fix)
Modify the update intervals in **BinanceBotCandles.class.php** line 128:

```php
$intervals = array( 
    "3m" => array( 1800, 30 ),    // Was 900 seconds, now 30 minutes
    "15m" => array( 3600, 160 ),  // Was 1800 seconds, now 60 minutes  
    "1h" => array( 7200, 600 )    // Was 3600 seconds, now 120 minutes
);
```

This reduces how often each symbol's candles are fetched.

### 2. **Limit Symbols Being Monitored** (Recommended)
Add a configuration setting to only monitor the top N trading pairs by volume instead of all pairs. This drastically reduces requests.

### 3. **Implement Request Weight Tracking**
Track your request weight and pause requests when approaching the limit:

```php
$weight = $this->_api->getXMbxUsedWeight1m();
if ($weight > 900) {  // Leave 300 weight buffer
    sleep(30);  // Wait before continuing
}
```

### 4. **Use WebSocket Instead** (Best practice)
Per Binance's message: *"Please use the websocket for live updates to avoid bans."* 

WebSocket connections consume no request weight and are ideal for real-time trading data. This requires refactoring to use a WebSocket library.

### 5. **Cache Aggressively**
Your code already has caching (cacheBalancesFile). Extend it to:
- Cache candlestick data longer
- Verify cache files aren't being invalidated too frequently
- Skip balance updates when holdings haven't changed

## Debug Steps

1. Check your Binance API key limits:
   ```bash
   curl -H "X-MBX-APIKEY: YOUR_KEY" https://api.binance.com/api/v3/account
   ```

2. Monitor request weights in real-time by adding logging to **bi-api.php** around line 1132-1134

3. Reduce the number of trading pairs being monitored in your **config.json**

## Prevention

- Start with only 10-20 important trading pairs, not all pairs
- Gradually increase update frequencies once stable
- Set a realistic `max_open_buy_orders` to reduce order checking frequency
- Contact Binance support if you need a higher rate limit for your use case
